apiVersion: v1
kind: Service
metadata:
  name: gok8s
  namespace: allocation
  labels:
    app: gok8s
spec:
  type: NodePort
  selector:
    app: gok8s
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31000