---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gok8s
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gok8s
  namespace: allocation
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gok8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gok8s
subjects:
  - kind: ServiceAccount
    name: gok8s
    namespace: allocation