package config

import "os"

var (
	PROMETHEUS_HOST	string
	PROMETHEUS_PORT	string
	ALGORITHM_HOST	string
	ALGORITHM_PORT	string
)

func init() {
	PROMETHEUS_HOST = os.Getenv("PROMETHEUS_SERVICE_HOST")
	PROMETHEUS_PORT = os.Getenv("PROMETHEUS_SERVICE_PORT")
	ALGORITHM_HOST = os.Getenv("CONTAINER-ALLOCATION_SERVICE_HOST")
	ALGORITHM_PORT = os.Getenv("CONTAINER-ALLOCATION_SERVICE_PORT")
}
