apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-allocation
  labels:
    app: container-allocation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-allocation
  template:
    metadata:
      labels:
        app: container-allocation
    spec:
      containers:
      - image: adachisakura/container-allocation
        imagePullPolicy: IfNotPresent
        name: container-allocation
        ports:
        - name: http
          containerPort: 8080