apiVersion: v1
kind: Service
metadata:
  name: container-allocation
  labels:
    app: container-allocation
spec:
  type: NodePort
  selector:
    app: container-allocation
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 32000